name: GitHub Classroom Workflow

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  build:
    name: Autograding
    runs-on: ["self-hosted"]
    steps:
      - uses: actions/checkout@v2
      - uses: education/autograding@v1
